from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stockData(object):
    def setupUi(self, stockData):
        stockData.setObjectName("stockData")
        stockData.resize(1034, 768)
        stockData.setAutoFillBackground(False)
        stockData.setStyleSheet("background-color: rgb(4, 4, 4);\n"
"alternate-background-color: rgb(226, 226, 226);")
        self.gridLayout_2 = QtWidgets.QGridLayout(stockData)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.labelTable = QtWidgets.QLabel(stockData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.labelTable.setFont(font)
        self.labelTable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelTable.setStyleSheet("labelTable{\n"
"color:rgb(226, 226, 226)\n"
"}")
        self.labelTable.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTable.setObjectName("labelTable")
        self.verticalLayout_20.addWidget(self.labelTable)
        self.tableWidget = QtWidgets.QTableWidget(stockData)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 800))
        self.tableWidget.setStyleSheet("background-color: rgb(160, 185, 207);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setRowCount(11)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(300)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_20.addWidget(self.tableWidget)
        self.line_3 = QtWidgets.QFrame(stockData)
        self.line_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_20.addWidget(self.line_3)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.labelType = QtWidgets.QLabel(stockData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.labelType.setFont(font)
        self.labelType.setObjectName("labelType")
        self.horizontalLayout_15.addWidget(self.labelType)
        self.figType = QtWidgets.QComboBox(stockData)
        self.figType.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.figType.setObjectName("figType")
        self.figType.addItem("")
        self.figType.addItem("")
        self.figType.addItem("")
        self.figType.addItem("")
        self.figType.addItem("")
        self.horizontalLayout_15.addWidget(self.figType)
        self.chgFig = QtWidgets.QPushButton(stockData)
        self.chgFig.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.chgFig.setObjectName("chgFig")
        self.horizontalLayout_15.addWidget(self.chgFig)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_15)
        self.graphicsView = QtWidgets.QGraphicsView(stockData)
        self.graphicsView.setStyleSheet("background-color: rgb(244, 248, 255);")
        self.graphicsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_19.addWidget(self.graphicsView)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.line_4 = QtWidgets.QFrame(stockData)
        self.line_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_20.addWidget(self.line_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.toolButton = QtWidgets.QToolButton(stockData)
        self.toolButton.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        self.path = QtWidgets.QLineEdit(stockData)
        self.path.setStyleSheet("background-color: rgba(221, 221, 221, 221);")
        self.path.setObjectName("path")
        self.horizontalLayout_3.addWidget(self.path)
        self.toCsv = QtWidgets.QPushButton(stockData)
        self.toCsv.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.toCsv.setObjectName("toCsv")
        self.horizontalLayout_3.addWidget(self.toCsv)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_20.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_20)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.labelID = QtWidgets.QLabel(stockData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setBold(True)
        font.setWeight(75)
        self.labelID.setFont(font)
        self.labelID.setStyleSheet("")
        self.labelID.setObjectName("labelID")
        self.horizontalLayout.addWidget(self.labelID)
        self.stockID = QtWidgets.QLineEdit(stockData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockID.sizePolicy().hasHeightForWidth())
        self.stockID.setSizePolicy(sizePolicy)
        self.stockID.setStyleSheet("background-color: rgba(221, 221, 221, 221);")
        self.stockID.setObjectName("stockID")
        self.horizontalLayout.addWidget(self.stockID)
        self.labelYear = QtWidgets.QLabel(stockData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setBold(True)
        font.setWeight(75)
        self.labelYear.setFont(font)
        self.labelYear.setObjectName("labelYear")
        self.horizontalLayout.addWidget(self.labelYear)
        self.year = QtWidgets.QLineEdit(stockData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year.sizePolicy().hasHeightForWidth())
        self.year.setSizePolicy(sizePolicy)
        self.year.setStyleSheet("background-color: rgba(221, 221, 221, 221);")
        self.year.setObjectName("year")
        self.horizontalLayout.addWidget(self.year)
        self.labelQuarter = QtWidgets.QLabel(stockData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setBold(True)
        font.setWeight(75)
        self.labelQuarter.setFont(font)
        self.labelQuarter.setObjectName("labelQuarter")
        self.horizontalLayout.addWidget(self.labelQuarter)
        self.quarter = QtWidgets.QComboBox(stockData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quarter.sizePolicy().hasHeightForWidth())
        self.quarter.setSizePolicy(sizePolicy)
        self.quarter.setMinimumSize(QtCore.QSize(200, 0))
        self.quarter.setMaximumSize(QtCore.QSize(300, 16777215))
        self.quarter.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.quarter.setObjectName("quarter")
        self.quarter.addItem("")
        self.quarter.addItem("")
        self.quarter.addItem("")
        self.quarter.addItem("")
        self.horizontalLayout.addWidget(self.quarter)
        self.subInfo = QtWidgets.QPushButton(stockData)
        self.subInfo.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.subInfo.setObjectName("subInfo")
        self.horizontalLayout.addWidget(self.subInfo)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(stockData)
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        self.title = QtWidgets.QLabel(stockData)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.title.setFont(font)
        self.title.setStyleSheet("background-color: rgb(7, 7, 7);")
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem7)
        self.line = QtWidgets.QFrame(stockData)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(stockData)
        QtCore.QMetaObject.connectSlotsByName(stockData)

    def retranslateUi(self, stockData):
        _translate = QtCore.QCoreApplication.translate
        stockData.setWindowTitle(_translate("stockData", "股票数据采集器"))
        self.labelTable.setText(_translate("stockData", "<html><head/><body><p><span style=\" color:#dddddd;\">股票数据表</span></p></body></html>"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("stockData", "日期"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("stockData", "开盘价"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("stockData", "收盘价"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("stockData", "最低价"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("stockData", "最高价"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("stockData", "成交量(手)"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("stockData", "成交金额(万元）"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("stockData", "换手率(%)"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("stockData", "振幅(%)"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("stockData", "涨跌幅(%)"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("stockData", "涨跌额"))
        self.labelType.setText(_translate("stockData", "<html><head/><body><p><span style=\" color:#dddddd;\">作图类型</span></p></body></html>"))
        self.figType.setItemText(0, _translate("stockData", "价格折线图"))
        self.figType.setItemText(1, _translate("stockData", "成交量柱状图"))
        self.figType.setItemText(2, _translate("stockData", "换手率折线图"))
        self.figType.setItemText(3, _translate("stockData", "振幅折线图"))
        self.figType.setItemText(4, _translate("stockData", "涨跌额折线图"))
        self.chgFig.setText(_translate("stockData", "点击绘制"))
        self.toolButton.setText(_translate("stockData", "..."))
        self.path.setText(_translate("stockData", "请输入保存路径"))
        self.toCsv.setText(_translate("stockData", "导出CSV"))
        self.labelID.setText(_translate("stockData", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#dddddd;\">股票编号</span></p></body></html>"))
        self.labelYear.setText(_translate("stockData", "<html><head/><body><p><span style=\" color:#dddddd;\">年份</span></p></body></html>"))
        self.labelQuarter.setText(_translate("stockData", "<html><head/><body><p><span style=\" color:#dddddd;\">季度</span></p></body></html>"))
        self.quarter.setItemText(0, _translate("stockData", "第一季度"))
        self.quarter.setItemText(1, _translate("stockData", "第二季度"))
        self.quarter.setItemText(2, _translate("stockData", "第三季度"))
        self.quarter.setItemText(3, _translate("stockData", "第四季度"))
        self.subInfo.setText(_translate("stockData", "提交"))
        self.title.setText(_translate("stockData", "<html><head/><body><p><span style=\" font-size:16pt; color:#dddddd;\">股票数据采集器</span></p></body></html>"))
